name: build-app
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: clone down
        uses: actions/checkout@v3
      - name: build application
        run: ci/build-app.sh
      - name: test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
