name: build-app
on: push

jobs:
  clone-project:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: clone down
        uses: actions/checkout@v3
      - name: upload repo
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: .

  build-project:
    runs-on: ubuntu-latest
    needs: clone-project
    container: gradle:6-jdk11
    steps:
      - name: download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: build application
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: test
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: upload repo
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: .

  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push docker
        uses: docker/build-push-action@v3
        with:
          context: app
          push: true
          tags: ghcr.io/${{ github.actor }}/micronaut-app:1.0-${{ github.sha }},ghcr.io/${{ github.actor }}/micronaut-app:latest

